#!/bin/bash

# Example usage of earthquake workflow

echo "========================================"
echo "EARTHQUAKE WORKFLOW EXAMPLE USAGE"
echo "========================================"

# Build Docker container (optional, if using locally)
echo ""
echo "1. Build Docker container:"
echo "   cd Docker"
echo "   docker build -f Earthquake_Dockerfile -t kthare10/earthquake-analysis:latest ."
echo "   docker push kthare10/earthquake-analysis:latest"

# Example 1: Single region (California)
echo ""
echo "2. Example 1: California earthquakes (M4.0+, January 2024)"
echo "   ./workflow_generator.py \\"
echo "       --regions california \\"
echo "       --start-date 2024-01-01 \\"
echo "       --end-date 2024-01-31 \\"
echo "       --min-magnitude 4.0 \\"
echo "       --output workflow_california.yml"

# Example 2: Multiple regions
echo ""
echo "3. Example 2: Multiple regions (California, Japan, Indonesia)"
echo "   ./workflow_generator.py \\"
echo "       --regions california japan indonesia \\"
echo "       --start-date 2024-01-01 \\"
echo "       --end-date 2024-01-31 \\"
echo "       --min-magnitude 4.5 \\"
echo "       --output workflow_multi_region.yml"

# Example 3: Pacific Ring of Fire (higher magnitude)
echo ""
echo "4. Example 3: Pacific Ring of Fire (M5.0+)"
echo "   ./workflow_generator.py \\"
echo "       --regions pacific_ring \\"
echo "       --start-date 2024-01-01 \\"
echo "       --end-date 2024-01-31 \\"
echo "       --min-magnitude 5.0 \\"
echo "       --output workflow_pacific.yml"

# Example 4: Worldwide significant earthquakes
echo ""
echo "5. Example 4: Worldwide significant earthquakes (M6.0+)"
echo "   ./workflow_generator.py \\"
echo "       --regions worldwide \\"
echo "       --start-date 2024-01-01 \\"
echo "       --end-date 2024-12-31 \\"
echo "       --min-magnitude 6.0 \\"
echo "       --output workflow_worldwide.yml"

# Example 5: Custom aftershock prediction settings
echo ""
echo "6. Example 5: Custom aftershock prediction (lower threshold)"
echo "   ./workflow_generator.py \\"
echo "       --regions japan \\"
echo "       --start-date 2024-01-01 \\"
echo "       --end-date 2024-06-30 \\"
echo "       --min-magnitude 4.0 \\"
echo "       --aftershock-threshold 4.5 \\"
echo "       --aftershock-time-windows 1 7 14 30 \\"
echo "       --output workflow_japan_aftershocks.yml"

# Example 6: Custom hazard assessment settings
echo ""
echo "7. Example 6: High-resolution hazard assessment"
echo "   ./workflow_generator.py \\"
echo "       --regions california \\"
echo "       --start-date 2020-01-01 \\"
echo "       --end-date 2024-12-31 \\"
echo "       --min-magnitude 3.5 \\"
echo "       --hazard-grid-resolution 0.5 \\"
echo "       --hazard-pga-thresholds 0.05 0.1 0.2 0.4 \\"
echo "       --output workflow_california_hazard.yml"

# Example 7: Custom seismic gap analysis settings
echo ""
echo "8. Example 7: Long-term seismic gap analysis"
echo "   ./workflow_generator.py \\"
echo "       --regions chile \\"
echo "       --start-date 2000-01-01 \\"
echo "       --end-date 2024-12-31 \\"
echo "       --min-magnitude 4.0 \\"
echo "       --gap-historical-years 30 \\"
echo "       --gap-recent-years 5 \\"
echo "       --gap-rate-threshold 0.25 \\"
echo "       --output workflow_chile_gaps.yml"

# Example 8: Full analysis with all custom settings
echo ""
echo "9. Example 8: Comprehensive analysis with all options"
echo "   ./workflow_generator.py \\"
echo "       --regions indonesia \\"
echo "       --start-date 2020-01-01 \\"
echo "       --end-date 2024-12-31 \\"
echo "       --min-magnitude 4.0 \\"
echo "       --cluster-method dbscan \\"
echo "       --cluster-eps 75 \\"
echo "       --cluster-min-samples 15 \\"
echo "       --aftershock-threshold 5.0 \\"
echo "       --hazard-grid-resolution 0.5 \\"
echo "       --gap-historical-years 20 \\"
echo "       --gap-recent-years 5 \\"
echo "       --output workflow_indonesia_full.yml"

# Submit workflow
echo ""
echo "10. Submit workflow to Pegasus:"
echo "    pegasus-plan --submit -s condorpool -o local workflow.yml"

# Monitor workflow
echo ""
echo "11. Monitor workflow status:"
echo "    pegasus-status /path/to/submit/directory"
echo "    pegasus-analyzer /path/to/submit/directory"

# Check outputs
echo ""
echo "12. Output files will be in output/ directory:"
echo "    <region>_catalog.csv                    - Raw earthquake data"
echo "    <region>_patterns.json                  - Statistical analysis"
echo "    <region>_visualization.png              - Earthquake visualization"
echo "    <region>_anomalies.json                 - Detected anomalies"
echo "    <region>_zones.json                     - Seismic zone clusters"
echo "    <region>_aftershock_predictions.json    - Aftershock probabilities"
echo "    <region>_aftershock_visualization.png   - Aftershock visualization"
echo "    <region>_seismic_hazard.json            - Hazard assessment"
echo "    <region>_hazard_visualization.png       - Hazard maps"
echo "    <region>_seismic_gaps.json              - Gap analysis"
echo "    <region>_gaps_visualization.png         - Gap visualization"

echo ""
echo "========================================"
echo "Available regions:"
echo "  - pacific_ring: Pacific Ring of Fire"
echo "  - california: California, USA"
echo "  - japan: Japanese archipelago"
echo "  - indonesia: Indonesian archipelago"
echo "  - turkey: Turkey and surroundings"
echo "  - chile: Chile"
echo "  - worldwide: Global (no bounding box)"
echo "========================================"
echo ""
echo "Workflow Options Summary:"
echo "  Clustering:  --cluster-method, --cluster-eps, --cluster-min-samples, --cluster-n-clusters"
echo "  Aftershock:  --aftershock-threshold, --aftershock-time-windows"
echo "  Hazard:      --hazard-grid-resolution, --hazard-pga-thresholds"
echo "  Gaps:        --gap-historical-years, --gap-recent-years, --gap-rate-threshold"
echo "========================================"
